#!/bin/sh
#
# @name IF750
#
# @type Quadrotor x
# @class Copter
#
# @output MAIN1 motor 1
# @output MAIN2 motor 2
# @output MAIN3 motor 3
# @output MAIN4 motor 4
#
# @output AUX1 feed-through of RC AUX1 channel
# @output AUX2 feed-through of RC AUX2 channel
# @output AUX3 feed-through of RC AUX3 channel
# @output AUX4 feed-through of RC FLAPS channel
#
# @maintainer Hyon Lim <lim@uvify.com>
#

echo "Executing IF750 script."

set VEHICLE_TYPE mc

set MIXER if750_IO
set PWM_OUT 12345

set MIXER_AUX if750_FMU
set PWM_AUX_OUT 1234

if [ $AUTOCNF = yes ]
then
	# First thing, reset all params to default... EXCEPT THIS LIST
	param reset_nostart RC* COM_FLTMODE* LND_FLIGHT_T_* TC_* CAL_ACC* CAL_GYRO* CAL_MAG* SENS_BOARD* EKF2_MAGBIAS*

	# Battery
	param set BAT_CAPACITY 8100
	param set BAT_CRIT_THR 0.25
	param set BAT_LOW_THR 0.30
	param set BAT_N_CELLS 6

	# Sensor calibration
	param set CAL_MAG0_ROT 0

	# MC
	param set MC_AIRMODE 0
	param set MC_DTERM_CUTOFF 25.0000
	param set MC_PITCHRATE_D 0.0050
	param set MC_PITCHRATE_I 0.1500
	param set MC_PITCHRATE_P 0.1300
	param set MC_PITCHRATE_MAX 70.0000
	param set MC_PITCH_P 5.1000
	param set MC_ROLLRATE_D 0.0050
	param set MC_ROLLRATE_I 0.1500
	param set MC_ROLLRATE_P 0.1300
	param set MC_ROLLRATE_MAX 70.0000
	param set MC_ROLL_P 5.1000
	param set MC_YAWRATE_I 0.2000
	param set MC_YAWRATE_MAX 100.0000
	param set MC_YAWRATE_P 0.4000
	param set MC_YAW_P 2.0000

	param set MPC_POS_MODE 3
	param set MPC_ACC_DOWN_MAX 1.0000
	param set MPC_ACC_UP_MAX 2.0000
	param set MPC_ACC_HOR 3.000
	param set MPC_ACC_HOR_MAX 3.000
	param set MPC_AUTO_MODE 0
	param set MPC_CRUISE_90 5.0000
	param set MPC_JERK_MIN 15.0000
	param set MPC_JERK_MAX 20.0000
	param set MPC_MAN_TILT_MAX 25.0000
	param set MPC_MAN_Y_MAX 60.0000
	param set MPC_SPOOLUP_TIME 3.0000
	param set MPC_THR_HOVER 0.35
	param set MPC_VEL_MANUAL 6.0
	
	param set MPC_XY_P 0.6
	param set MPC_XY_TRAJ_P 1.0000
	param set MPC_XY_VEL_P 0.1500
	param set MPC_XY_VEL_I 0.3
	param set MPC_XY_VEL_D 0.005
	param set MPC_XY_VEL_MAX 8.0000
	param set MPC_XY_CRUISE 3.0000

	param set MPC_YAW_MODE 3
	param set MPC_Z_VEL_P 0.3000
	param set MPC_Z_VEL_I 0.3500
	param set MPC_Z_VEL_D 0.0
	param set MPC_Z_VEL_MAX_DN 2.0
	param set MPC_Z_VEL_MAX_UP 5.0
	param set MPC_Z_TRAJ_P 1.0
	param set MPC_LAND_SPEED 0.5000
	param set MPC_THR_MIN 0.10
	param set MPC_TILTMAX_AIR 25.0000
	param set MPC_TKO_RAMP_T 1
	param set MPC_YAW_EXPO 0.6000
	param set MPC_Z_MAN_EXPO 0.6000
	param set MPC_XY_MAN_EXPO 0.7000

	param set NAV_ACC_RAD 1.0

	param set PWM_MIN 1000
	param set PWM_MAX 2000
	param set PWM_RATE 400
	param set SYS_USE_IO 1
	param set PWM_SBUS_MODE 1
	param set THR_MDL_FAC 0.5
	param set PWM_AUX_DISARMED 900
	param set PWM_AUX_FAIL1 900
	param set PWM_AUX_FAIL2 900
	param set PWM_AUX_FAIL3 900
	param set PWM_AUX_FAIL4 900
	param set PWM_AUX_MIN 1050
	param set PWM_AUX_RATE 400
	param set PWM_MAIN_DIS1 2000
	param set PWM_MAIN_DIS3 1050
	param set PWM_MAIN_DIS4 1500
	param set PWM_MAIN_DIS5 900
	param set PWM_MAIN_FAIL3 1050
	param set PWM_MAIN_FAIL4 1500
	param set PWM_MAIN_FAIL5 2000
	param set SENS_EN_LL40LS 2
	param set SENS_FLOW_MAXHGT 15.0000
	param set IMU_GYRO_CUTOFF 40.0000

	param set MAV_0_CONFIG 101
	param set MAV_0_FORWARD 1
	param set MAV_0_MODE 0
	param set MAV_0_RATE 0

	param set MAV_1_CONFIG 102
	param set MAV_1_FORWARD 1
	param set MAV_1_MODE 2
	param set MAV_1_RATE 0

	param set MAV_2_CONFIG 104
	param set MAV_2_FORWARD 1
	param set MAV_2_MODE 2
	param set MAV_2_RATE 0

	param set SER_TEL1_BAUD 115200
	param set SER_TEL2_BAUD 921600
	param set SER_TEL4_BAUD 115200

	param set MNT_MODE_IN 0
	param set MNT_MODE_OUT 1
	param set MNT_MAN_PITCH 1
	param set MNT_RANGE_PITCH 180
	param set MNT_RANGE_ROLL 90

	param set RTL_DESCEND_ALT 5.0000
	param set RTL_LAND_DELAY 0.0000
	param set RTL_RETURN_ALT 30.0000
	param set RTL_CONE_ANG 45
	param set SDLOG_DIRS_MAX 20
	param set SDLOG_MODE 0
	param set SDLOG_PROFILE 3
	param set TRIG_MODE 1
	param set TRIG_INTERFACE 3
	param set TRIG_PINS 56
	param set BAT_N_CELLS 6
	param set BAT_A_PER_V 58
	param set BAT_V_CHARGED 4.2000
	param set BAT_V_DIV 11.2700
	param set BAT_CRIT_THR 0.35
	param set BAT_EMERGEN_THR 0.10
	param set BAT_LOW_THR 0.40
	param set CBRK_IO_SAFETY 22027
	param set COM_DISARM_LAND 1
	param set COM_RC_OVERRIDE 1
	param set SYS_FORCE_F7DC 2

	param set EKF2_AID_MASK 35
	param set EKF2_BCOEF_X 45.0000
	param set EKF2_BCOEF_Y 45.0000
	param set EKF2_GND_EFF_DZ 4.0000
	param set EKF2_GPS_POS_X 0.0000
	param set EKF2_GPS_POS_Y 0.1800
	param set EKF2_GPS_POS_Z -0.1600
	param set EKF2_HGT_MODE 1
	param set EKF2_IMU_POS_X 0.0
	param set EKF2_IMU_POS_Y 0.0
	param set EKF2_IMU_POS_Z -0.075
	param set EKF2_OF_POS_X -0.1740
	param set EKF2_OF_POS_Z 0.2300
	param set EKF2_PCOEF_XN -0.1000
	param set EKF2_PCOEF_XP -0.1000
	param set EKF2_PCOEF_YN -0.1000
	param set EKF2_PCOEF_YP -0.1000
	
	# Range sensors
	param set EKF2_RNG_POS_X -0.1410
	param set EKF2_RNG_POS_Z 0.2300
	param set EKF2_RNG_AID 1

	param set SENS_BOARD_ROT 4

	# GPS
	param set GPS_UBX_DYNMODEL 8
	param set GPS_1_CONFIG 201
	param set GPS_YAW_OFFSET 0.0000
fi

echo "End of executing IF750 script."
